"use client";
import {ArrowRight,CheckCircle2,Clock3,Euro,PackagePlus,Send,ShoppingCart} from "lucide-react";
import {initialOrders,money} from "@/lib/crm-data";
import type {ScreenId} from "./Sidebar";
const statusClass=(s:string)=>s==="Reçue"?"received":s==="Envoyée"?"sent":"draft";
export function Dashboard({onNavigate}:{onNavigate:(id:ScreenId)=>void}){return <div className="screen">
 <div className="welcome-row"><div><span className="eyebrow">JEUDI 13 AOÛT 2026</span><h1>Bonjour <span>👋</span></h1><p>Voici où en sont les achats de HM Group.</p></div><button className="primary-btn" onClick={()=>onNavigate("new-order")}><PackagePlus size={18}/>Nouvelle commande</button></div>
 <div className="stats-grid"><Stat icon={<ShoppingCart/>} label="Commandes ce mois" value="12" note="+3 depuis juillet" tone="blue"/><Stat icon={<Euro/>} label="Total commandé" value="14 820 €" note="Août 2026" tone="green"/><Stat icon={<Clock3/>} label="En attente" value="3" note="À suivre" tone="amber"/><Stat icon={<CheckCircle2/>} label="Réceptionnées" value="8" note="Ce mois-ci" tone="violet"/></div>
 <div className="dashboard-grid"><section className="panel recent-panel"><div className="panel-head"><div><h2>Commandes récentes</h2><p>Les dernières commandes fournisseurs</p></div><button className="text-btn" onClick={()=>onNavigate("orders")}>Tout voir <ArrowRight size={16}/></button></div><div className="order-list">{initialOrders.slice(0,3).map(o=><div className="order-row" key={o.id}><div className="supplier-icon"><ShoppingCart size={18}/></div><div className="order-main"><strong>{o.supplier}</strong><span>{o.id} · {o.products} produits</span></div><div className="order-date">{o.date}</div><div className="order-total"><strong>{money(o.total)}</strong><span className={"status "+statusClass(o.status)}>{o.status}</span></div></div>)}</div></section>
 <section className="panel quick-panel"><div className="panel-head"><div><h2>Accès rapides</h2><p>Les actions fréquentes</p></div></div><Quick icon={<PackagePlus/>} title="Créer une commande" text="Répartir entre les filiales" tone="blue" onClick={()=>onNavigate("new-order")}/><Quick icon={<ShoppingCart/>} title="Gérer les produits" text="Catalogue et fournisseurs" tone="violet" onClick={()=>onNavigate("products")}/><Quick icon={<Send/>} title="Suivre les commandes" text="Envois et réceptions" tone="green" onClick={()=>onNavigate("orders")}/></section></div>
 </div>}
function Stat({icon,label,value,note,tone}:{icon:React.ReactNode;label:string;value:string;note:string;tone:string}){return <div className="stat-card"><div className={"stat-icon "+tone}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function Quick({icon,title,text,tone,onClick}:{icon:React.ReactNode;title:string;text:string;tone:string;onClick:()=>void}){return <button className="quick-action" onClick={onClick}><span className={"quick-icon "+tone}>{icon}</span><span><strong>{title}</strong><small>{text}</small></span><ArrowRight size={17}/></button>}
