"use client";
import {useMemo,useState} from "react";
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Minus,Package,Plus,Search,Send,Users} from "lucide-react";
import {companies,type CompanyKey,money,products} from "@/lib/crm-data";
import type {ScreenId} from "./Sidebar";
type Teams=Record<CompanyKey,number>; type Selected=Record<number,number>;
export function NewOrder({onNavigate}:{onNavigate:(id:ScreenId)=>void}){
 const [step,setStep]=useState(1),[teams,setTeams]=useState<Teams>({cpte:3,pose:4,instal:2,pac:2}),[supplier,setSupplier]=useState("IS Électrique"),[selected,setSelected]=useState<Selected>({1:11,2:11,3:6}),[query,setQuery]=useState(""),[sent,setSent]=useState(false);
 const totalTeams=Math.max(1,Object.values(teams).reduce((a,b)=>a+b,0));
 const filtered=products.filter(p=>p.offers.some(o=>o.supplier===supplier)&&p.name.toLowerCase().includes(query.toLowerCase()));
 const total=useMemo(()=>Object.entries(selected).reduce((sum,[id,qty])=>{const o=products.find(p=>p.id===Number(id))?.offers.find(x=>x.supplier===supplier);return sum+(o?.price||0)*qty},0),[selected,supplier]);
 const team=(key:CompanyKey,value:number)=>setTeams(t=>({...t,[key]:Math.max(0,value)})),qty=(id:number,value:number)=>setSelected(s=>({...s,[id]:Math.max(0,value)}));
 const sharesFor=(n:number)=>{let used=0;return companies.map((c,i)=>{const value=i===companies.length-1?Math.max(0,n-used):Math.min(n-used,Math.round(n*teams[c.key]/totalTeams));used+=value;return value})};
 if(sent)return <div className="screen success-screen"><div className="success-card"><div className="success-icon"><Check size={34}/></div><span className="eyebrow">COMMANDE ENREGISTRÉE</span><h1>Prête à être envoyée</h1><p>La commande <strong>CMD-2026-049</strong> a été créée pour {supplier}. Le bon fournisseur ne contient aucune information sur les équipes.</p><div className="success-actions"><button className="secondary-btn" onClick={()=>onNavigate("orders")}>Voir les commandes</button><button className="primary-btn"><Send size={17}/>Ouvrir l’e-mail</button></div></div></div>;
 return <div className="screen"><div className="page-title"><div><button className="back-link" onClick={()=>onNavigate("dashboard")}><ArrowLeft size={17}/>Retour</button><h1>Nouvelle commande</h1><p>Créez et répartissez une commande fournisseur.</p></div><div className="draft-tag">Brouillon automatique</div></div>
 <div className="stepper">{["Équipes","Produits","Répartition","Validation"].map((label,i)=><div key={label} className={"step "+(step===i+1?"active ":"")+(step>i+1?"done":"")}><span>{step>i+1?<Check size={15}/>:i+1}</span><div><small>ÉTAPE {i+1}</small><strong>{label}</strong></div></div>)}</div>
 <section className="panel wizard-panel">
 {step===1&&<div className="wizard-content"><Heading icon={<Users/>} title="Nombre d’équipes par société" text="Ces valeurs servent uniquement au calcul de la répartition."/><div className="teams-grid">{companies.map(c=><div className="team-card" key={c.key}><div className="company-line"><span className="company-dot" style={{background:c.color}}/><div><strong>{c.name}</strong><small>Nombre d’équipes</small></div></div><NumberControl value={teams[c.key]} onMinus={()=>team(c.key,teams[c.key]-1)} onPlus={()=>team(c.key,teams[c.key]+1)}/></div>)}</div><Info icon={<Users/>} title={totalTeams+" équipes au total"} text="La répartition sera calculée proportionnellement entre les quatre sociétés."/></div>}
 {step===2&&<div className="wizard-content"><Heading icon={<Package/>} title="Sélection des produits" text="Les quantités sont toujours saisies en couronnes, boîtes, cartons, sachets ou pièces."/><div className="product-toolbar"><label>FOURNISSEUR<select value={supplier} onChange={e=>{setSupplier(e.target.value);setSelected({})}}><option>IS Électrique</option><option>Rexel</option><option>Sonepar</option></select></label><div className="search-box"><Search size={18}/><input placeholder="Rechercher un produit…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="select-products">{filtered.map(p=>{const o=p.offers.find(x=>x.supplier===supplier)!,n=selected[p.id]||0;return <div className={"select-product "+(n?"chosen":"")} key={p.id}><div className="product-check">{n?<Check size={15}/>:null}</div><div className="product-copy"><strong>{p.name}</strong><span>{o.brand} · Réf. {o.reference}</span><small>{o.packaging} · {o.packagingType==="modifiable"?"Modifiable":"Fixe"}</small></div><strong className="unit-price">{money(o.price)}<small>/ {p.unit.toLowerCase()}</small></strong><NumberControl compact value={n} onMinus={()=>qty(p.id,n-1)} onPlus={()=>qty(p.id,n+1)}/></div>})}</div></div>}
 {step===3&&<div className="wizard-content"><Heading icon={<Users/>} title="Répartition par société" text="Le dispatch est calculé selon le nombre d’équipes. Vous pourrez le corriger."/><div className="dispatch-table"><div className="dispatch-head"><span>Produit</span><span>Total</span>{companies.map(c=><span key={c.key}>{c.short}</span>)}</div>{Object.entries(selected).filter(([,q])=>q>0).map(([id,n])=>{const p=products.find(x=>x.id===Number(id))!,shares=sharesFor(n);return <div className="dispatch-row" key={id}><span><strong>{p.name}</strong><small>{p.unit}</small></span><span className="global-qty">{n}</span>{shares.map((v,i)=><span className="dispatch-input" key={companies[i].key}>{v}</span>)}</div>})}</div><Info icon={<CheckCircle2/>} title="Contrôle automatique activé" text="La somme des quatre filiales correspond toujours à la quantité globale."/></div>}
 {step===4&&<div className="wizard-content"><Heading icon={<CheckCircle2/>} title="Bon fournisseur" text="Vérifiez le document avant de créer la commande."/><div className="supplier-document"><div className="doc-brand"><div className="brand-mark">HM</div><div><strong>HM GROUP</strong><small>BON DE COMMANDE FOURNISSEUR</small></div><div className="doc-meta"><strong>CMD-2026-049</strong><span>13/08/2026</span></div></div><div className="delivery-box"><small>LIVRAISON</small><strong>HM Group</strong><span>Adresse de livraison configurée dans les paramètres</span></div><div className="doc-table"><div><span>PRODUIT</span><span>COND.</span><span>QTÉ</span><span>CPTE</span><span>POSE</span><span>INSTAL</span><span>PAC</span></div>{Object.entries(selected).filter(([,q])=>q>0).map(([id,n])=>{const p=products.find(x=>x.id===Number(id))!,o=p.offers.find(x=>x.supplier===supplier)!,shares=sharesFor(n);return <div key={id}><span><strong>{o.supplierName}</strong><small>{o.reference} · {o.brand}</small></span><span>{o.packaging}</span><span><strong>{n}</strong></span>{shares.map((value,index)=><span key={companies[index].key}>{value}</span>)}</div>})}</div><div className="doc-note">Le nombre d’équipes n’apparaît jamais sur ce document.</div></div></div>}
 <div className="wizard-footer"><div>{step>1&&<button className="secondary-btn" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>Précédent</button>}</div><div className="footer-summary"><span>{Object.values(selected).filter(q=>q>0).length} produit(s) · <strong>{money(total)}</strong></span>{step<4?<button className="primary-btn" onClick={()=>setStep(step+1)}>Continuer <ArrowRight size={17}/></button>:<button className="primary-btn" onClick={()=>setSent(true)}><Check size={17}/>Créer la commande</button>}</div></div>
 </section></div>
}
function Heading({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="wizard-heading"><span className="section-icon">{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="info-strip">{icon}<span><strong>{title}</strong><small>{text}</small></span></div>}
function NumberControl({value,onMinus,onPlus,compact}:{value:number;onMinus:()=>void;onPlus:()=>void;compact?:boolean}){return <div className={"number-control "+(compact?"compact":"")}><button onClick={onMinus}><Minus size={16}/></button><strong>{value}</strong><button onClick={onPlus}><Plus size={16}/></button></div>}
